### ISSUE TITLE
Var change for reagent 0.5.0 not contained in kioo 0.4.1-SNAPSHOT

### ISSUE THREAD

**Issue by LiFlash** [ckirkendall/kioo#44]
I just checked out the reagent-template and added kioo "0.4.1-SNAPSHOT" to the dependencies. Now I get the complie error 
`Referred var reagent.impl.template/as-component does not exist at line 1`

Is the commit for changing the var missing in the snapshot?

**Comment by wilkerlucio** [comment]
I'm having the same issue here.

**Comment by wilkerlucio** [comment]
@ckirkendall can you please update the snapshot release? I noticed that you have a commit that already seems to fix the issue c6fcd94da257406d17261213b3b97b92384f836a

**Comment by timgilbert** [comment]
I've hit this too, and a new release to clojars would be great. FWIW, as a workaround, you can clone the project locally, `lein install` it, and then use `[kioo "0.4.1-SNAPSHOT" :exclusions [org.clojure/clojure]]` in your project.clj.

**Comment by JulianLeviston** [comment]
@timgilbert I just tried your workaround but I seem to be getting "as-component does not exist at line 1..." errors when compiling. Have you had any amazing insights on this recently?

**Comment by ckirkendall** [comment]
I will try to put a snapshot release out tonight

**Comment by JulianLeviston** [comment]
You, sir, are a gentleman, and worthy of good praise. This, then, is such good praise! :) :+1:

**Comment by ckirkendall** [comment]
I pushed up the snapshot last night.  Please test it if everything goes ok, I will cut 0.4.2.
