### ISSUE TITLE
do-> with a lifecycle or a listen on react events seems to short circuit renders

### ISSUE THREAD

**Issue by gigasquid** [ckirkendall/kioo#58]
When we have some code like:

```clojure
(do->
  (listen :onUpdate (fn [e] (.log js/console "not printing")))
  (content "Not rendered"))
```
The same thing happens with the lifecycle

```clojure
(do->
  (lifecycle {:will-mount blah :will-update blah}))
  (content "Not rendered"))
```

Flipping the order of the expressions also short circuits.

Here is the funny bit: listening to the onRender gets the events, but the kioo content still doesn't happen

```clojure
(do->
  (listen :onRender (fn [e] (.log js/console "does print!")))
  (content "Not rendered"))
```
onRender's behavior stays the same even if you swap expression order.

**Comment by gigasquid** [comment]
Found part of the problem.   It seems to work if the lifecycle includes :should-update returning true

```clojure
(do->
     (content (:copy-data app))
     (lifecycle  {:should-update (fn [this next-props next-state] true) ;; This needs to be here
                      :did-update (fn [this prev-props prev-state] do-all-the-things)))}))
```

**Comment by ckirkendall** [comment]
Thank you for finding this.  I have pushed a fix up and would love if you could test it.

**Comment by gigasquid** [comment]
Works great!  Thanks :fish_cake:
