### ISSUE TITLE
kioo + progressive enhancement

### ISSUE THREAD

**Issue by johncowie** [ckirkendall/kioo#59]
Do be honest this isn't an issue with kioo, but more of a question:  How possible would it be to load templates at runtime instead of compile time?

I'd ideally like to use something like kioo to do progressive enhancement (i.e. receive generated HTML from the server, and then enhance it with JS).  In more code-y terms, something like:
```clojure
(kioo/component (.-body js/document) [:#main]
     {[:h1] (content (:header @data))
      ; ...etc 
       })
```

Has this not been done because..
 - a) parsing html at runtime is hard?
 - b) it's a terrible idea for other reasons?
 - c) it just hasn't been done yet?
 - d) what are you talking about that's totally a thing you can do already!

Would really appreciate some input before I embark on trying to fill this gap :-p

**Comment by ckirkendall** [comment]
levand (Luke Vandarhart) is working on a kioo lite that allows just that.  There are some performance issues with this approach but he was able to port enlive to Clojurescript.    https://github.com/levand/enlive

**Comment by johncowie** [comment]
Ah ok awesome.  Thanks for the pointer, will try and chip in with that effort.
