### ISSUE TITLE
Kioo and lein-figwheel

### ISSUE THREAD

**Issue by 0tus** [ckirkendall/kioo#67]
Hello,

I'm trying to use kioo with lein-figwheel and reagent. No changes are detected on HTML files.

Is there a simple way to make this work ?

Aside question from a novice: why not putting HTML templates into the `src` folder since they actually are source files? Wouldn't they automatically be watched by figwheel this way?

Thanks

**Comment by ckirkendall** [comment]
Check out https://github.com/ckirkendall/kioo/issues/9  
This is the method I use to handle this.

**Comment by ckirkendall** [comment]
duplicate of https://github.com/ckirkendall/kioo/issues/9
