### ISSUE TITLE
kioo 0.5.0?

### ISSUE THREAD

**Issue by fredZen** [ckirkendall/kioo#74]
Hi

I‘ve noticed that there is a [0.5.0 release of kioo](https://clojars.org/kioo/versions/0.5.0) on Clojars, but the [corresponding commit](https://github.com/ckirkendall/kioo/commit/d332a0a72222991c96e2dbaf5619739a5987f172) doesn’t appear to be on github. Now I’m wondering if it’s a good idea to use that version or not.

- maybe 0.5.0 is an official release, and you just forgot to push to github
- maybe 0.5.0 is an official release, but you won’t or can’t publish the source code on github, at least not now (I’ve seen this happen for all sorts of good reasons with open source projects)
- maybe releasing 0.5.0 was an accident, and I shouldn’t use it (I can imagine that removing a version from clojars would be difficult)
- maybe I’m no good at mind-reading and I should just ask, hence this issue ;-)

**Comment by ckirkendall** [comment]
@fredZen - thanks for pointing that out.  I completely missed pushing the changes up.

**Comment by fredZen** [comment]
And thank you for giving us Kioo! With enlive being fairly niche, I was surprised and delighted that there was a ‘port’ to Clojurescript / react, and that’s event maintained!
